### ISSUE TITLE
Single file mode with special char "\" does not work

### ISSUE THREAD

**Issue by ael-code** [ael-code/pydirl#10]
To recreate the bug: 
- create a file named "a1\a2"
- serve it through pydirl using single file mode
- use chrome without specifing the complete uri. Use only the http://ip:port (eg: 127.0.0.1:5000)

Chrome says too many redirects :(

**Comment by zmcode** [comment]
http://stackoverflow.com/questions/21715132/python-how-to-send-file-from-filesystem-with-a-unicode-filename
